### ISSUE TITLE
Publishing as a Firefox version?

### ISSUE THREAD

**Issue by xileftenurb** [tomer8007/spotify-web-ads-remover#1]
Hello, I reviewed your app and it look really nice,

I'm wondering if it's complicated to add the app as a firefox add ons (since the script is browser agnostic)?

My research seem to show it would probably work out of the box if you publish it to firefox:addons

**Comment by tomer8007** [comment]
Yes, it's probably a matter of replacing `chrome` with `browser` like [this](https://github.com/tomer8007/whatsapp-web-incognito/pull/29/files), and then loading it into Firefox using the devloper page.

**Comment by xileftenurb** [comment]
I created a pull request following that pattern
