### ISSUE TITLE
Disconnects the connection with authorised apps such as Discord

### ISSUE THREAD

**Issue by sujalgoel** [tomer8007/spotify-web-ads-remover#10]
If I am listening to my playlist and there is an ad, it is removed by the extension but it disrupts the connection with my discord status and I have to refresh the spotify page to reconnect it.

**Comment by tomer8007** [comment]
Do you hear the ad? Anyway do you have javascript errors in console?

**Comment by sujalgoel** [comment]
I don't hear the ad but the problem is disconnectivity with discord status.

**Comment by sujalgoel** [comment]
and I am not sure about console errors but it isn't related to your extension.

**Comment by sujalgoel** [comment]
any updates?
