### ISSUE TITLE
In Chrome when the ad appears, the music drops out 

### ISSUE THREAD

**Issue by carroyo1** [tomer8007/spotify-web-ads-remover#11]
Hi,

I am noticing these days that in Chrome the music is not playing after the ad [blocked] appears. It stops, I have to refresh the web hoping It'd work.

**Comment by UberSuperBoss** [comment]
I have the same issue. But I'm not sure if it's the fault of this extension. Ublock Origin has also stopped working for stopping the spotify ads. Maybe it was something done by spotify?

**Comment by tomer8007** [comment]
@UberSuperBoss Yes, it appears that this is something done by Spotify.

**Comment by tomer8007** [comment]
Seems to be gone now
