### ISSUE TITLE
"Another device is playing" when it isn't

### ISSUE THREAD

**Issue by grzkr** [tomer8007/spotify-web-ads-remover#12]
Since last Browser Update (Microsoft Edge Chromium) I always get the Error that there is an active play on a other tab, but it is not.
It is the only one Tab open with https://open.spotify.com, no other tab is playing anything (no youtube, no other stream)

![2022-09-23_VOhbvTWbKs](https://user-images.githubusercontent.com/70884172/191910714-7d0202f3-15a4-423b-b896-afd8c2efffde.png)

**Comment by tomer8007** [comment]
Thank you for reporting, does this happen only in Edge or also in Chrome?

**Comment by grzkr** [comment]
Now I have tested it in Chrome, an there it works without any Error.
Therefore it is only in Microsoft Edge Chromium

**Comment by Dave---** [comment]
Just tried on Edge too, same error. (Edge and Chrome both latest versions etc. Tried on Win 10 PC and Laptop too.) :(

**Comment by grzkr** [comment]
After I tested it again in Chrome latest version I got the same error when I want to start playing "Liked" songs.
The error is on Chrome, and Microsoft Edge Chromium

**Comment by tomer8007** [comment]
I think this error does not happen anymore. @Dave--- @grzkr Do you encounter it?

**Comment by Dave---** [comment]
Sorry, I’ve not used it for quite some time.
