### ISSUE TITLE
Stops playing after a while and only works again after refreshing

### ISSUE THREAD

**Issue by tomtosen** [tomer8007/spotify-web-ads-remover#14]
Sometimes it happens after an hour or more, sometimes after just a few songs.
It stops playing, play button is stuck on pause and when I try to hit play or start another song, it plays advertisements.

After refresh it works perfectly fine again.
I am not to bothered, because the app is already great and very useful and I dont mind refreshing ever now and then when my music stops, however maybe there is a fix for this IDK.

**Comment by tomer8007** [comment]
Hi, thank you for opening the issue here.

If you can provide some javascript errors when this is happening it will be very useful for me to understand the problem.

**Comment by tomtosen** [comment]
I would be glad to, if you can tell me how to do it?
What would be the easiest way for you?

Here is a capture of what it looks like btw.
![Capture_scrubbed](https://user-images.githubusercontent.com/104476662/232740414-0cf4d04a-9e65-4c4c-8b77-b4db8f74606e.png)

**Comment by tomtosen** [comment]
After taking that screenshot, I realized I was using "Spotify Playback Speed" extension form chrome webstore, in addition to yours.

I have since uninstalled it, to see if it was interfering with your extension.

Will get back to you ASAP.

**Comment by tomtosen** [comment]
Looks like "Spotify Playback Speed" extension was interfering with your extension.
Everything works fine now, thanks anyways!

**Comment by tomer8007** [comment]
Interesting finding.

I still want to support that extension too, so if you could open the javascript console (F12) and get some errors from it, it will be helpful.
