### ISSUE TITLE
chrome 91 issue

### ISSUE THREAD

**Issue by sergio49** [tomer8007/spotify-web-ads-remover#3]
Hi,

on my chrome 91, I got this even atfer refresh or open / close chrome.
![image](https://user-images.githubusercontent.com/57832052/124394186-96847880-dcfe-11eb-947a-8c37a0d7a121.png)

**Comment by tomer8007** [comment]
Thanks for reporting. I see you're in version 1.0.6. Does it happen in version 1.0.7 too? I can't reproduce this.
