### ISSUE TITLE
"Interception is not fully working" error

### ISSUE THREAD

**Issue by forkbabu** [tomer8007/spotify-web-ads-remover#4]
![Screenshot from 2021-07-18 14-33-41](https://user-images.githubusercontent.com/8037297/126062435-f66cf18b-418d-40a5-a0f4-5f965355d4ae.png)

**Comment by tomer8007** [comment]
Chrome version?

**Comment by forkbabu** [comment]
@tomer8007 Version 91.0.4472.114 (Official Build) (64-bit)

**Comment by tomer8007** [comment]
Can't reproduce this. Any javascript errors in the JS console?

**Comment by tankaras** [comment]
> Can't reproduce this. Any javascript errors in the JS console?

I got the same message a couple of times recently. In the event it happens again, how can I help? as a Noob user.

**Comment by tankaras** [comment]
> > Can't reproduce this. Any javascript errors in the JS console?
> 
> I got the same message a couple of times recently. In the event it happens again, how can I help? as a Noob user.

Update: This is from Cltr+Shift+J 
Don't know if it helps

Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
8Ignoring duplicate Content-Security-Policy directive 'script-src'.
sentry.io/api/114855/envelope/?sentry_key=de32132fc06e4b28965ecf25332c3a25&sentry_version=7:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
open.spotify.com/:1 Ignoring duplicate Content-Security-Policy directive 'script-src'.
VM22:1 Uncaught TypeError: Cannot redefine property: rwt
    at Function.defineProperty (<anonymous>)
    at <anonymous>:1:8
cdn.cookielaw.org/scripttemplates/otSDKStub.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
vendor~web-player.9875bcc9.js:1 Uncaught (in promise) Event
vendor~web-player.9875bcc9.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:7r2Jg8x3ZExWU9O2y32Yta
spclient.wg.spotify.com/track-playback/v1/devices/undefined/state:1 Failed to load resource: the server responded with a status of 404 ()
vendor~web-player.9875bcc9.js:1 TypeError: Cannot read property 'states' of undefined
    at getNextState (ads_removal.js:286)
    at manipulateStateMachine (ads_removal.js:170)
    at async ads_removal.js:73
(anonymous) @ vendor~web-player.9875bcc9.js:1
vendor~web-player.9875bcc9.js:1 SpotifyAdRemover: Shortned ad at spotify:ad:7r2Jg8x3ZExWU9O2y32Yta
vendor~web-player.9875bcc9.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:1ymXbNXshpVYTko1VzaPvJ
vendor~web-player.9875bcc9.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:7r2Jg8x3ZExWU9O2y32Yta
vendor~web-player.9875bcc9.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:1ymXbNXshpVYTko1VzaPvJ
vendor~web-player.9875bcc9.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:7r2Jg8x3ZExWU9O2y32Yta
vendor~web-player.9875bcc9.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:1ymXbNXshpVYTko1VzaPvJ
vendor~web-player.9875bcc9.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:7r2Jg8x3ZExWU9O2y32Yta
vendor~web-player.9875bcc9.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:1ymXbNXshpVYTko1VzaPvJ
2DevTools failed to load source map: Could not load content for https://open.spotify.com/service-worker.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://open.scdn.co/cdn/build/web-player/vendor~web-player.9875bcc9.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://open.scdn.co/cdn/build/web-player/web-player.2edae8c4.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://open.scdn.co/cdn/build/web-player/xpui-routes-home.d7888f9d.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://open.scdn.co/cdn/build/web-player/774.49795ba4.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://open.scdn.co/cdn/build/web-player/418.e6243a61.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://open.scdn.co/cdn/build/web-player/480.e745e06e.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://open.scdn.co/cdn/build/web-player/xpui-routes-show.da25d7cb.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
vendor~web-player.9875bcc9.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:7r2Jg8x3ZExWU9O2y32Yta
vendor~web-player.9875bcc9.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:1ymXbNXshpVYTko1VzaPvJ
vendor~web-player.9875bcc9.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:7r2Jg8x3ZExWU9O2y32Yta
vendor~web-player.9875bcc9.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:1ymXbNXshpVYTko1VzaPvJ
vendor~web-player.9875bcc9.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:7r2Jg8x3ZExWU9O2y32Yta
vendor~web-player.9875bcc9.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:1ymXbNXshpVYTko1VzaPvJ

**Comment by tomer8007** [comment]
@tankaras Thanks a lot, it does help. I see the problem arises from not being able to detect the currently playing device. Are you listening on another device? What's your configuration? I now understood this could prevent the ads removal.

@forkbabu If you could provide the same log that would be helpful too

**Comment by tankaras** [comment]
> @tankaras Thanks a lot, it does help. I see the problem arises from not being able to detect the currently playing device. How many devices are you using and who's playing? I now understood this could also prevent the ads removal.
> 

Glad am able to help.

> How many devices are you using and who's playing?

Spotify was playing on one device i.e from one user, when I captured above log. Though my use case may be slightly different as I use spotify exclusively as a PWA app.

**Comment by tomer8007** [comment]
@tankaras I've commit c106b24c0672a131d0fba0cd1f238b9f6ec740b8 to try to improve that, please tell me if it changes anything for you.

**Comment by tankaras** [comment]
> @tankaras I've commit [c106b24](https://github.com/tomer8007/spotify-web-ads-remover/commit/c106b24c0672a131d0fba0cd1f238b9f6ec740b8) to try to improve that, please tell me if it changes anything for you.

Tested extensively since the update. All fine on my end. Thank you  @tomer8007
