### ISSUE TITLE
Doesn't skip some ads, nextState is null

### ISSUE THREAD

**Issue by TimWel** [tomer8007/spotify-web-ads-remover#6]
![image](https://user-images.githubusercontent.com/32878506/137092516-e93e8433-2f66-43b5-8ffc-4b82d394c02d.png)
Hey!

First of all, awesome extension and works really well! Except for this mcdonalds advertisement, it seem to mute it, but then it just stops, it stays on 0:20 - 0:20 and it will never go to the next song. Is this something on my end or is this a bug?

Thanks!

P.S. I am using spotify as an Windows 10 app from the website "Install this site as an app".

**Comment by TimWel** [comment]
No problem 😄, as soon as I get the error I will send the output here.

**Comment by TimWel** [comment]
Alright, thanks!

**Comment by tomer8007** [comment]
@TimWel This should be fixed now, please tell me if it seems to work/you somehow encounter the issue again.
